import Head from "next/head";
import { Input, Button, CardHeader, CardBody } from "@material-tailwind/react";
import { signIn, useSession } from "next-auth/react";
import Image from "next/image";
import { useEffect, useState } from "react";
import { useRouter } from "next/router";

export default function Home({ data }) {
  const [username, setUsername] = useState(null);

  const router = useRouter();

  const [password, setPassword] = useState(null);
  const handleSub = async (elemen) => {
    elemen.preventDefault();
    if ((username !== null, password !== null)) {
      await signIn("credentials", {
        username: username,
        password: password,
        // redirect: false,
        callbackUrl: "/company/dashboard",
      }).then((res) => console.log());
    } else {
      console.log("gagal");
    }
  };
  return (
    <>
      <Head>
        <title>Grosir Management System</title>;
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen flex flex-row justify-center bg-white ">
        <div className="relative flex-1 h-screen">
          <Image
            src="/splashimage-1.jpg"
            fill
            className="w-12"
            alt="splash"
            priority
          />
        </div>
        <div
          className="w-96 h-96 bg-white p-5 flex justify-center fixed mt-28 text-c"
          onSubmit={handleSub}
        >
          <div className="w-96 h-min">
            <CardHeader color="transparent" className="mx-0 mt-0 shadow-none">
              <h2 className="mb-2 text-lg">Form</h2>
              <h2 className="text-4xl font-semibold mb-5">Login</h2>
            </CardHeader>
            <CardBody className="flex flex-col gap-3 p-0">
              <Input
                label="Username"
                color="deep-orange"
                onChange={(e) => {
                  setUsername(e.target.value);
                }}
              />
              <Input
                label="Password"
                color="deep-orange"
                type={"password"}
                onChange={(e) => {
                  setPassword(e.target.value);
                }}
              />
              <Button color="deep-orange" onClick={handleSub}>
                Submit
              </Button>
              <p>Fill the required credentials</p>
            </CardBody>
          </div>
        </div>
      </main>
    </>
  );
}
